version: "3"
services:
  express:
    container_name: app
    restart: always
    build: ./
    ports:
      - "8080:8000"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
